---
name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed # Ensures it runs when a PR is merged

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start Docker Service
        run: sudo service docker start # Ensure Docker daemon is running

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose-plugin -y

      - name: Build Docker containers
        run: docker compose build # Updated to docker compose

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py test" # Updated to docker compose

      - name: Run Lint
        run: docker compose run --rm app sh -c "flake8" # Updated to docker compose
