---
name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed # Ensure the workflow runs on PR merge

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start Docker Service
        run: sudo service docker start # Ensure Docker daemon is running

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker Compose is pre-installed in the GitHub Actions environment
      - name: Build Docker containers
        run: docker compose build

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py test"

      - name: Run Lint
        run: docker compose run --rm app sh -c "flake8"
