---
name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04

    services:
      docker:
        image: docker:19.03.12
        options: --privileged # To run Docker inside the GitHub Action runner
        ports:
          - 2375:2375

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Build Docker containers
        run: docker compose build

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py test"

      - name: Run Lint
        run: docker compose run --rm app sh -c "flake8"
